### ISSUE TITLE
分页控制器组件

### ISSUE THREAD

**Issue by samuncle** [liucaide/CD#9]
分页控制器组件能实现点击菜单的时候才加载数据吗

**Comment by liucaide** [comment]
默认只加载当前页面。

可设置  Page.Model，预加载相邻页面
/// 同时加载当前页面的前后 loadNextNum 个页面
public var loadNextNum:Int = 0

**Comment by liucaide** [comment]
默认只加载当前页面。

可设置  Page.Model，预加载相邻页面
/// 同时加载当前页面的前后 loadNextNum 个页面
public var loadNextNum:Int = 0
